### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by KSCHdsc** [cas1m1r/GITTER#1]
nice Job bro but what does your code actually do?

**Comment by cas1m1r** [comment]
There's some code to return all the repos that match a keyword. Another function will checkout the branch and look for emails in commit messages. 

I have to clean this up for sure! And thank you!

**Comment by cas1m1r** [comment]
Eventually I will want to use a dataset of this info pass into a NLP model that can start to classify maliciousness based on a bunch of different attributes about code uploaded.

**Comment by cas1m1r** [comment]
For exampe, I can use GitStuff class, enter your username and get a summary of your contributions on github. Then spidering out and scanning all the repositories of the users referenced in your projects. 
![image](https://user-images.githubusercontent.com/50683460/217799286-73a9c074-527c-4203-9885-e34faf8e3e12.png)
